### ISSUE TITLE
Jumps from 150 to 275

### ISSUE THREAD

**Issue by davidshumway** [kmitz/Regul#2]
This is occurring on one machine. Will test:

Tue Mar 15 15:47:56 UTC 2016
TEMP REGULATION IS ACTIVE
Temperature: 54
Frequence: 150
Increase the power........ Only 54 Celsius degrees
New Frequency: 4:275:0a82
Restarting

Testing:
`[dave@localhost AntMiner]$ FREQ_STEP=1;freq=150; echo $(cat freqList | grep -B "$FREQ_STEP" "$freq" | head -n 1)`
`4:275:0a82`
`[dave@localhost AntMiner]$ FREQ_STEP=1;freq=143.75; echo $(cat freqList | grep -B "$FREQ_STEP" "$freq" | head -n 1)`
`8:150:0b83`
`[dave@localhost AntMiner]$ FREQ_STEP=1;freq=156.25; echo $(cat freqList | grep -B "$FREQ_STEP" "$freq" | head -n 1)`
`8:162.5:0c83`

Solved:
Here is the problem: `[dave@localhost AntMiner]$ FREQ_STEP=1;freq=150; echo $(cat freqList | grep -B "$FREQ_STEP" "$freq")`
`4:275:0a82 4:268.75:1506 -- 8:156.25:0c03 8:150:0b83`
And here is a solution:
`[dave@localhost AntMiner]$ FREQ_STEP=1;freq=150; echo $(cat freqList | grep -B "$FREQ_STEP" "$freq:")`
`8:156.25:0c03 8:150:0b83`
That is:
`[dave@localhost AntMiner]$ FREQ_STEP=1;freq=150; echo $(cat freqList | grep -B "$FREQ_STEP" "$freq:" | head -n 1)`
`8:156.25:0c03`

**Comment by kmitz** [comment]
Closing issue after merging associated fix. 
By the way, there is another potential issue: the frequency adjustments are not bounded. The script will fail when trying to downclock below 100MHz or overclock above 500MHz. This is an edge case but I'll open a new issue for warning at least.
